FROM php:8.1-fpm
WORKDIR /var/www/html
COPY . .
RUN apt-get update && apt-get install -y \
    libzip-dev zip unzip \
    && docker-php-ext-install zip pdo_mysql
CMD ["php", "artisan", "serve", "--host=127.0.0.1", "--port=8000"]
